# fly.toml app configuration file generated for field-notes on 2023-05-22T21:59:35-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "field-notes"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "2m0s"

[build]
  dockerfile = "Dockerfile"